# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
version=1.6
group=com.boundingelf10.fec

# Dependencies
fabric_api_version=0.157.0+26.2

flashback_version=HkyawEi6
essential_version=1.4.1.1
kotlin_version=2.3.0
essential_modrinth_version=F6WKM1HY
modmenu_version=njXb639R
devlogin_version=0.1.0.5
